sudo: false

env:
  global:
    - PYTHONUNBUFFERED=yes
    - secure: "TyC3F7uBmd4iWLpUyhIDkpRfbhPUmRqFeFhr12VSHfzODQfeLBqB9hHMhhjVLlk1gsQwIXzNDY2X82U83d4gG0X+SEPDUpTimuWc/GJoJLQL4+uyfpS8seQWnxa7ZXkZrUdKb2owHtx+0ESzZwfOg+pd0OxoMenK9bcGo3hZtkk="

# apt-get is only available to the Ubuntu tests (os: linux)
# the other tests (os: osx) uses Homebrew to install shell
# dependencies and is done in ./utils/travis-install.sh
addons:
  apt:
    packages:
      - zsh
      - csh
      - tcsh
      - posh
      - ksh


matrix:
  include:
    - python: '2.7'
      os: linux
      language: python
    - python: '3.4'
      os: linux
      language: python
    - python: '3.6'
      os: linux
      language: python
    - python: '3.5'
      env: FLAKE8=true
      os: linux
      language: python
    - os: osx
      env: PYTHON_VERSION=3.5
      language: generic
    - python: '3.5'
      env: CONDA_BUILD=2.0.12
      os: linux
      language: python
    - python: '3.5'
      env: CONDA_BUILD=2.1.1
      os: linux
      language: python


install:
  - source ./utils/travis-install.sh

script:
  - source ./utils/travis-script.sh

sudo: false

after_success:
  - pip install codecov coveralls scrutinizer-ocular
  - codecov --env PY_VERSION
  - coveralls || true
  - ocular || true
