language: python
python:
  # We don't actually use the system Python but this keeps it organized.
  - "2.7"
  - "3.3"
install:
  # TODO: Use a "latest" url
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.0.0-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.0.0-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda install setuptools
  - python setup.py develop
  - conda install pytest
  - conda info -a

script: py.test

notifications:
    flowdock: ef3821a08a791106512ccfc04c92eccb
