language: python
python:
  # We don't actually use the system Python but this keeps it organized.
  - "2.7"
  - "3.3"
  - "3.4"
env:
  -
  - PYCOSAT=0.6.0
install:
  # TODO: Use a "latest" url
  - sudo apt-get update
  - sudo apt-get install zsh
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.5.2-Linux-x86_64.sh -O miniconda.sh;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.3" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda3-3.0.0-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.5.2-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda install pytest requests mock
  - if [[ "$PYCOSAT" ]]; then
      conda install pycosat=$PYCOSAT;
    fi
  - python setup.py install
  - conda info -a

script: py.test

notifications:
    flowdock: ef3821a08a791106512ccfc04c92eccb
