environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\appveyor\\run_with_env.cmd"
  COVERALLS_REPO_TOKEN:
    secure: ZaE7K9EHorv40AjYhSuWtQeRAsMN1+QqPf7u8rOlvEY50kdaHj87Mh5GIDZgJBzj

  matrix:
    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
    # - PYTHON: "C:\\Python34_64"
    #   PYTHON_VERSION: "3.4"
    #   PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
    # - PYTHON: "C:\\Python27_32"
    #   PYTHON_VERSION: "2.7"
    #   PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python35_32"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %HOMEDRIVE%%HOMEPATH%

install:
  - powershell .\utils\appveyor-killold.ps1
  - call .\utils\appveyor-install.bat

# Not a .NET project, we build scikit-image in the install step instead
build: false

test_script:
  - call .\utils\appveyor-script.bat

on_success:
  - pip install codecov coveralls scrutinizer-ocular
  - codecov --env PYTHON_VERSION
  # - coveralls && exit 0
  # - ocular && exit 0
