environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34_32"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34_64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"

#    - PYTHON: "C:\\Python35_32"
#      PYTHON_VERSION: "3.5"
#      PYTHON_ARCH: "32"
#
#    - PYTHON: "C:\\Python35_64"
#      PYTHON_VERSION: "3.5"
#      PYTHON_ARCH: "64"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %HOME%

install:
  # - utils/win_build_env.cmd
  - powershell ./utils/install.ps1
  - set PATH=%HOME%/miniconda;%HOME%/miniconda/Scripts;%$HOME%/miniconda/Library/bin;%PATH%
  - conda info
  - conda config --set always_yes yes
  - conda install --force --no-deps conda requests
  # - conda info python
  - python -c "import sys; print(sys.version)"
  - python -c "import sys; print(sys.executable)"
  - python -c "import sys; print(sys.prefix)"
  - conda install -q python=%PYTHON_VERSION%
  - conda install -q -c conda pytest requests mock pycrypto pyflakes pycosat
  - conda install -q pip
  - conda install -q git psutil
  - pip install auxlib flake8 pytest-cov
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - python setup.py install --old-and-unmanageable


# Not a .NET project, we build scikit-image in the install step instead
build: false

test_script:
  - py.test --cov conda --cov-report xml tests --shell=cmd.exe --shell=bash

on_success:
  - pip install codecov
  - codecov --env PYTHON_VERSION
