image: Visual Studio 2017

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\appveyor\\run_with_env.cmd"
  COVERALLS_REPO_TOKEN:
    secure: ZaE7K9EHorv40AjYhSuWtQeRAsMN1+QqPf7u8rOlvEY50kdaHj87Mh5GIDZgJBzj

  matrix:
     - PYTHON: "C:\\Python36_64"
       PYTHON_VERSION: "3.6"
       PYTHON_ARCH: "64"
       PYTHON_ROOT: "C:\\Miniconda36-x64"

     - PYTHON: "C:\\Python36_64"
       PYTHON_VERSION: "3.6"
       PYTHON_ARCH: "64"
       SHELL_INTEGRATION: true
       PYTHON_ROOT: "C:\\Miniconda36-x64"

     - PYTHON: "C:\\Python27_32"
       PYTHON_VERSION: "2.7"
       PYTHON_ARCH: "32"
       PYTHON_ROOT: "C:\\Miniconda"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %HOME%
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - "%PYTHON_ROOT%\\Scripts\\conda install -y -c defaults -c conda-forge python=%PYTHON_VERSION% pycosat conda requests ruamel_yaml pytest pytest-cov pytest-timeout mock responses pexpect xonsh"
  # conda install -y -c defaults -c conda-forge pytest pytest-cov pytest-timeout mock responses pexpect xonsh
  - "%PYTHON_ROOT%\\Scripts\\pip install codecov"
  - "%PYTHON_ROOT%\\python -m conda init --install"
  - "%PYTHON_ROOT%\\python -m conda init --dev"
  - dir C:\Miniconda36-x64\conda-meta

build: false

test_script:
  - dev-init.bat
  - conda info
  - set "ADD_COV=--cov-report xml --cov-report term-missing --cov conda"
  - IF NOT DEFINED SHELL_INTEGRATION py.test %ADD_COV% -m "not integration and not installed" -v
  - IF NOT DEFINED SHELL_INTEGRATION py.test %ADD_COV% --cov-append -m "integration and not installed" -v
  - IF NOT DEFINED SHELL_INTEGRATION codecov --env PYTHON_VERSION --flags integration --required
  - IF NOT DEFINED SHELL_INTEGRATION python -m conda.common.io
  - IF DEFINED SHELL_INTEGRATION python -m conda._vendor.auxlib.packaging conda  # this hard-codes __version__ in conda/__init__.py to speed up tests
  - IF DEFINED SHELL_INTEGRATION py.test %ADD_COV% -m "installed" --shell=bash.exe --shell=cmd.exe
