channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - argh=0.26.2=py37_1001
  - asn1crypto=0.24.0=py37_1003
  - babel=2.6.0=py_1
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2019.3.9=hecc5488_0
  - certifi=2019.3.9=py37_0
  - cffi=1.12.3=py37h8022711_0
  - chardet=3.0.4=py37_1003
  - commonmark=0.7.5=py_0
  - conda-package-handling=1.0.4=py37_0
  - cryptography=2.6.1=py37h72c5cf5_0
  - docutils=0.14=py37_1001
  - future=0.17.1=py37_1000
  - icu=58.2=hf484d3e_1000
  - idna=2.8=py37_1000
  - imagesize=1.1.0=py_0
  - jinja2=2.10.1=py_0
  - libarchive=3.3.3=hc3f970e_1004
  - libffi=3.2.1=he1b5a44_1006
  - libiconv=1.15=h516909a_1005
  - libxml2=2.9.9=h13577e0_0
  - livereload=2.6.0=py_0
  - lz4-c=1.8.3=he1b5a44_1001
  - lzo=2.10=h14c3975_1000
  - markupsafe=1.1.1=py37h14c3975_0
  - ncurses=6.1=hf484d3e_1002
  - openssl=1.1.1b=h14c3975_1
  - packaging=19.0=py_0
  - pathtools=0.1.2=py_1
  - pip=19.1=py37_0
  - port-for=0.4=py_1
  - pycosat=0.6.3=py37h14c3975_1001
  - pycparser=2.19=py37_1
  - pygments=2.3.1=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pysocks=1.6.8=py37_1002
  - python=3.7.3=h5b0a415_0
  - python-libarchive-c=2.8=py37_1004
  - pytz=2019.1=py_0
  - pyyaml=5.1=py37h14c3975_0
  - readline=7.0=hf8c457e_1001
  - requests=2.21.0=py37_1000
  - ruamel_yaml=0.15.71=py37h14c3975_1000
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_1000
  - snowballstemmer=1.2.1=py_1
  - sphinx=2.0.1=py_0
  - sphinx-argparse=0.2.5=py_0
  - sphinx-autobuild=0.7.1=py_2
  - sphinx_rtd_theme=0.4.3=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-programoutput=0.11=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.1=py_0
  - sqlite=3.26.0=h67949de_1001
  - tk=8.6.9=h84994c4_1001
  - tornado=6.0.2=py37h516909a_0
  - tqdm=4.31.1=py_0
  - urllib3=1.24.2=py37_0
  - watchdog=0.8.3=py_2
  - wheel=0.33.1=py37_0
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zlib=1.2.11=h14c3975_1004
  - zstd=1.3.3=1
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - pip:
    - libarchive-c==2.8