name: sphinx
channels:
  - conda-forge
dependencies:
  - Pillow==10.1.0
  - Sphinx<9
  - boltons>=23.0.0
  - conda-sphinx-theme==0.3.0
  - frozendict>=2.4.2
  - linkify-it-py==2.0.2
  - myst-parser==2.0.0
  - pluggy==1.3.0
  - pylint==3.0.2
  - requests>=2.28.0,<3
  - ruamel.yaml>=0.11.14,<0.19
  - sphinx-argparse==0.5.2
  - sphinx-autoapi==3.0.0
  - sphinx-autobuild==2021.3.14
  - sphinx-reredirects==0.1.5
  - sphinx-sitemap==2.5.1
  - sphinx-design==0.5.0
  - sphinx-copybutton==0.5.2
  - sphinxcontrib-applehelp==1.0.7
  - sphinxcontrib-devhelp==1.0.5
  - sphinxcontrib-htmlhelp==2.0.4
  - sphinxcontrib-jsmath==1.0.1
  - sphinxcontrib-mermaid==0.9.2
  - sphinxcontrib-programoutput==0.17
  - sphinxcontrib-qthelp==1.0.6
  - sphinxcontrib-serializinghtml==1.1.9
  - tqdm>=4
  - conda-libmamba-solver>=25.4.0
  - pip>25
  - pip:
      - sphinxcontrib-plantuml==0.21
