name: Automate Issues

on:
  # NOTE: github.event is issue_comment payload:
  # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment
  issue_comment:
    types: [created]

env:
  FEEDBACK_LBL: pending::feedback
  SUPPORT_LBL: pending::support

jobs:
  # NOTE: will update label if anyone responds, not just the author/reporter
  # TODO: create conda-issue-sorting team and modify this to toggle label based on
  # whether a non-issue-sorting engineer commented
  pending_support:
    # if [pending::feedback] and anyone responds
    if: >-
      !github.event.repository.fork
      && !github.event.issue.pull_request
      && contains(github.event.issue.labels.*.name, 'pending::feedback')
    runs-on: ubuntu-latest
    steps:
      # remove [pending::feedback]
      - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.2.0
        with:
          labels: ${{ env.FEEDBACK_LBL }}
          github_token: ${{ secrets.PROJECT_TOKEN }}
      # add [pending::support], if still open
      - uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # v1.1.3
        if: github.event.issue.state == 'open'
        with:
          labels: ${{ env.SUPPORT_LBL }}
          github_token: ${{ secrets.PROJECT_TOKEN }}
