name: Automate Issues

on:
  # NOTE: github.event is issue_comment payload:
  # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment
  issue_comment:
    types: [created]

env:
  FEEDBACK_LBL: pending::feedback
  SUPPORT_LBL: pending::support

jobs:
  # NOTE: doesn't catch cases where multiple users act as the author/reporter,
  # this is just an effort to catch the majority of support cases
  # TODO: create conda-issue-sorting team and modify this to toggle label based on
  # whether a non-issue-sorting engineer commented
  pending_support:
    # if [pending::feedback] and the author responds
    if: >-
      !github.event.repository.fork
      && github.event_name == 'issue_comment'
      && github.event.action == 'created'
      && !github.event.issue.pull_request
      && contains(github.event.issue.labels.*.name, 'pending::feedback')
      && github.event.issue.user.login == github.event.comment.user.login
    runs-on: ubuntu-latest
    steps:
      # remove [pending::feedback]
      - uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: ${{ env.FEEDBACK_LBL }}
          github_token: ${{ secrets.PROJECT_TOKEN }}
      # add [pending::feedback], if still open
      - uses: actions-ecosystem/action-add-labels@v1.1.0
        if: github.event.issue.state == 'open'
        with:
          labels: ${{ env.SUPPORT_LBL }}
          github_token: ${{ secrets.PROJECT_TOKEN }}
