---
name: Sync Labels

on:
  # NOTE: github.event is workflow_dispatch payload:
  # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'dryrun: Preview changes to labels without editing them (true|false)'
        required: true
        type: boolean
        default: true

jobs:
  sync:
    if: '!github.event.repository.fork'
    runs-on: ubuntu-latest
    env:
      GLOBAL: https://raw.githubusercontent.com/conda/infra/main/.github/global.yml
      LOCAL: .github/labels.yml
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - id: has_local
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6
        with:
          files: ${{ env.LOCAL }}
      - name: Global Only
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a
        if: steps.has_local.outputs.files_exists == 'false'
        with:
          config-file: ${{ env.GLOBAL }}
          delete-other-labels: true
          dry-run: ${{ github.event.inputs.dryrun }}
      - name: Global & Local
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a
        if: steps.has_local.outputs.files_exists == 'true'
        with:
          config-file: |
            ${{ env.GLOBAL }}
            ${{ env.LOCAL }}
          delete-other-labels: true
          dry-run: ${{ github.event.inputs.dryrun }}
